### ISSUE TITLE
Zano SDK Documentation offline

### ISSUE THREAD

**Issue by xmakina** [torquing/libZanoDotNet#2]
http://www.torquinggroup.com/zanosdk/ is offline, presumably it got knocked out as part of the overhaul of the Torquing Group website.

Is there a mirror of the documentation, or will it be migrated to the Github wiki?

**Comment by robinzano** [comment]
I've talked to our web team, and it wasn't moved over when our servers crashed. They are looking into moving it over.

**Comment by douglasresende** [comment]
:+1:

**Comment by xmakina** [comment]
Any update on when this will be happening?
