### ISSUE TITLE
Updating Drone Configuration / Unexpected PowerOff looping

### ISSUE THREAD

**Issue by xmakina** [torquing/libZanoDotNet#3]
[Zano+28549] INF Unexpected PowerOff
[Zano+28549]     Attempting to Connect.
[Zano+28550] INF +++ Status: 701:0
[Zano+28853] INF +++ Status: 702:0
[Zano+28853]     Established Connection.
[Zano+28954]     Attempting to Boot.
[Zano+30957]     Sending out version request.
[Zano+31660] INF +++ Status: 703:0
[Zano+33070]     Loaded 190 API functions.
[Zano+33170]     Loaded 22 API errors.
[Zano+33272]     Loaded 3 API constants.
[Zano+33272]     Bootloader: 1.0.4.0
[Zano+33272]     Firmware: 1.1.4.51
[Zano+33274]     Serial: ad02000001000000
[Zano+33275]     Recovery: 0
[Zano+33276]     Boot Count: 3
[Zano+33278]     Installed: 1.4.51, Best Available: 1.4.51. Should Upgrade = False
[Zano+33279]     Partially Connected.
[Zano+33380]     Received X = 780
[Zano+33380]     Received Y = 282
[Zano+33381]     Received Z = -352
[Zano+33381] INF +++ Status: 201:0
[Zano+33382] INF Updating Drone Configuration to 780 282 -352
[Zano+33384] INF +++ Status: 202:0
[Zano+33987] INF Unexpected PowerOff
[Zano+33987]     Attempting to Connect.

Loops continually

**Comment by robinzano** [comment]
Hello,

I'll be releasing libZano 1.1.x later this week, which I think may fix your issues. We've never seen this happen, and it's odd to see it doing something like that. Can you paste the full log in if you don't mind?

Kind Regards,

Robin

**Comment by xmakina** [comment]
C:\Code\Junk\Zano\Examples\GetAltitude\bin\Debug [master +5 ~1 -0 !]> .\GetAltitude.exe
[Zano+00000] INF libZano 1.0.0 Windows (Release)
[Zano+00000] INF (c) Torquing Robotics Ltd 2015. SDK Release. Not for redistribution.
[Zano+00004] INF Established UDP Socket to 192.168.0.1:10001
[Zano+00004] INF +++ Status: 301:0
[Zano+00006]     Attempting to Connect.
[Zano+00006] INF +++ Status: 701:0
[Zano+00007]     [DNS] DNS Probe Attempt
[Zano+00022]     We have internet!
[Zano+00056]     Connected to account.flyzano.com
[Zano+00199]     [Social] Received Hello
[Zano+00199]     [Updates] Firmware 1.1.4.51 installed. Asking for a newer version.
[Zano+00199] INF +++ Status: 401:0
[Zano+00200]     [HTTP] Newing HTTP Connection due to refreshing
[Zano+00237]     [Updates] Asking for new Firmware with minimum version of 1.1.4.51
[Zano+00237]     [HTTP] Obtained client 006AEF28 for service type: 7
[Zano+00237]     ***\* Obtained Web Login
[Zano+00237] INF +++ Status: 302:0
[Zano+00237]     [HTTP] Newing HTTP Connection due to refreshing
[Zano+00385] INF +++ Status: 403:0
[Zano+00385]     [Updates] No newer firmware available.
[Zano+00441]     Loaded Drone Configuration.
[Zano+00442] INF +++ Status: 702:0
[Zano+00442]     Established Connection.
[Zano+00443] INF +++ Status: 703:0
[Zano+00596]     Web Logged In as 'cf0734b7d4436c9fc946cc02f97be782c783890208f3aaf5956ed56f2be010c4':1882
[Zano+00596] INF +++ Status: 501:0
[Zano+00596]     [HTTP] Newing HTTP Connection due to refreshing
[Zano+00627]     [Updates] Asking for Firmware Configuration
[Zano+00627] INF +++ Status: 1001:0
[Zano+00715]     Loaded 190 API functions.
[Zano+00748]     Loaded 22 API errors.
[Zano+00759]     Loaded 3 API constants.
[Zano+00759]     Bootloader: Unknown
[Zano+00760]     Firmware: 1.1.4.51
[Zano+00760]     Serial: ad02000001000000
[Zano+00760]     Recovery: 0
[Zano+00760]     Boot Count: 1
[Zano+00760]     Installed: 1.4.51, Best Available: 1.4.51. Should Upgrade = False
[Zano+00760]     Partially Connected.
[Zano+00782]     Received X = 780
[Zano+00782]     Received Y = 282
[Zano+00782]     Received Z = -352
[Zano+00782] INF +++ Status: 201:0
[Zano+00783] INF Updating Drone Configuration to 780 282 -352
[Zano+00783] INF +++ Status: 202:0
[Zano+00804] INF +++ Status: 505:0
[Zano+00804]     [Updates] Received Firmware Configuration
[Zano+00804]     Loaded Drone Configuration.
[Zano+00838]     Data rate is set to 20
[Zano+01156] INF Unexpected PowerOff
[Zano+01156]     Attempting to Connect.
[Zano+01157] INF +++ Status: 701:0
[Zano+01202] INF +++ Status: 702:0
[Zano+01202]     Established Connection.
[Zano+01213]     Attempting to Boot.
[Zano+03216]     Sending out version request.
[Zano+03786] INF +++ Status: 703:0
[Zano+04236]     Loaded 190 API functions.
[Zano+04258]     Loaded 22 API errors.
[Zano+04280]     Loaded 3 API constants.
[Zano+04280]     Bootloader: 1.0.4.0
[Zano+04281]     Firmware: 1.1.4.51
[Zano+04282]     Serial: ad02000001000000
[Zano+04284]     Recovery: 0
[Zano+04285]     Boot Count: 2
[Zano+04287]     Installed: 1.4.51, Best Available: 1.4.51. Should Upgrade = False
[Zano+04288]     Partially Connected.
[Zano+04300]     Data rate is set to 22
[Zano+04311]     Received X = 780
[Zano+04311]     Received Y = 282
[Zano+04313]     Received Z = -352
[Zano+04314] INF +++ Status: 201:0
[Zano+04315] INF Updating Drone Configuration to 780 282 -352
[Zano+04316] INF +++ Status: 202:0
[Zano+04404]     Data rate is set to 20
[Zano+04687] INF Unexpected PowerOff
[Zano+04687]     Attempting to Connect.
[Zano+04687] INF +++ Status: 701:0
[Zano+04732] INF +++ Status: 702:0
[Zano+04732]     Established Connection.
[Zano+04743]     Attempting to Boot.
[Zano+06746]     Sending out version request.
[Zano+07413] INF +++ Status: 703:0
[Zano+07875]     Loaded 190 API functions.
[Zano+07897]     Loaded 22 API errors.
[Zano+07919]     Loaded 3 API constants.
[Zano+07919]     Bootloader: 1.0.4.0
[Zano+07919]     Firmware: 1.1.4.51
[Zano+07921]     Serial: ad02000001000000
[Zano+07922]     Recovery: 0
[Zano+07922]     Boot Count: 3
[Zano+07924]     Installed: 1.4.51, Best Available: 1.4.51. Should Upgrade = False
[Zano+07925]     Partially Connected.
[Zano+07948]     Received X = 780
[Zano+07948]     Received Y = 282
[Zano+07948]     Received Z = -352
[Zano+07950] INF +++ Status: 201:0
[Zano+07951] INF Updating Drone Configuration to 780 282 -352
[Zano+07953] INF +++ Status: 202:0
[Zano+07965]     Data rate is set to 22
[Zano+08052]     Data rate is set to 20
[Zano+08324] INF Unexpected PowerOff
[Zano+08325]     Attempting to Connect.
[Zano+08325] INF +++ Status: 701:0
[Zano+08370] INF +++ Status: 702:0
[Zano+08371]     Established Connection.
[Zano+08381]     Attempting to Boot.
[Zano+10389]     Sending out version request.
[Zano+10946] INF +++ Status: 703:0
[Zano+11186]     Loaded 190 API functions.
[Zano+11208]     Loaded 22 API errors.
[Zano+11230]     Loaded 3 API constants.
[Zano+11230]     Bootloader: 1.0.4.0
[Zano+11231]     Firmware: 1.1.4.51
[Zano+11232]     Serial: ad02000001000000
[Zano+11234]     Recovery: 0
[Zano+11235]     Boot Count: 4
[Zano+11235]     Installed: 1.4.51, Best Available: 1.4.51. Should Upgrade = False
[Zano+11237]     Partially Connected.
[Zano+11259]     Received X = 780
[Zano+11259]     Received Y = 282
[Zano+11260]     Received Z = -352
[Zano+11262] INF +++ Status: 201:0
[Zano+11265] INF Updating Drone Configuration to 780 282 -352
[Zano+11265] INF +++ Status: 202:0
[Zano+11310]     Data rate is set to 20
[Zano+11614] INF Unexpected PowerOff
[Zano+11614]     Attempting to Connect.
[Zano+11616] INF +++ Status: 701:0
[Zano+11661] INF +++ Status: 702:0
[Zano+11661]     Established Connection.
[Zano+11672]     Attempting to Boot.

**Comment by xmakina** [comment]
Any update on the release of 1.1?
